package com.ltnc.be.domain.employee;

public enum DegreeType {
  BACHELOR_OF_MEDICINE,
  BACHELOR_OF_MEDICAL_SCIENCES,
  BACHELOR_OF_PUBLIC_HEALTH,
  BACHELOR_OF_SURGERY,
  BACHELOR,
  DOCTOR_OF_MEDICINE
}
